### ISSUE TITLE
UnicodeDecodeError when redering synthetic data

### ISSUE THREAD

**Issue by jyzhuu** [yoterel/STORM-Net#10]
Hello,
I'm running this program on Windows and encountered this error with default settings. For the template model file, I used the adultTemplate.txt and also tried other model files but none of them worked. Here are the error messages and I wonder if you have any clues regarding this issue? 

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\14993\miniconda3\envs\env\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "C:\Users\14993\Documents\STORM-Net-master\CapCalibrator\video_annotator.py", line 811, in render
    elif self.is_renderer_active():
  File "C:\Users\14993\Documents\STORM-Net-master\CapCalibrator\video_annotator.py", line 790, in is_renderer_active
    return file_io.is_process_active(self.renderer_executable.name)
  File "C:\Users\14993\Documents\STORM-Net-master\CapCalibrator\file_io.py", line 176, in is_process_active
    output = subprocess.check_output(call).decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd0 in position 0: invalid continuation byte

Many thanks!

**Comment by yoterel** [comment]
Hi there, this is a new error I haven't seen before, can you please post here your operating system version, python version, and the output from `conda list` when the environment is activated? I will try to reproduce on my end.
P.S. what step are you trying to perform? (offline step?) which button are you pressing specifically? (I'm assuming "render"?) can you confirm that you are actually pointing to the renderer executable in the other fields? (the default settings won't work most probably, you will need to manually select the renderer executable at the very least).

**Comment by jyzhuu** [comment]
Hello, thanks for replying! 

I'm running this on Windows 10 (64bit), python version 3.7.16, conda list is attached below.
![condalist1](https://github.com/yoterel/STORM-Net/assets/159587999/3d2ab917-a115-460e-8cdf-b87a12a7c510)
![condalist2](https://github.com/yoterel/STORM-Net/assets/159587999/9c5b8247-1473-4bda-b406-b7d6af339214)
![condalist3](https://github.com/yoterel/STORM-Net/assets/159587999/e346d760-3a09-41ac-b313-c103bdece728)
![condalist4](https://github.com/yoterel/STORM-Net/assets/159587999/e19e27c7-bcc7-4fe4-8a4a-576ccec3ce45)

I'm trying to do the offline steps and changed the path to each file manually so I guess this might not be the reason. Here is the files I chose:
Template model file: C:\Users\14993\Documents\STORM-Net-master\example_models\adultTemplate.txt
Renderer: C:\Users\14993\Documents\STORM-Net-master\DataSynth\build\DataSynth.exe
Synthesized data output folder: C:\Users\14993\Documents\STORM-Net-master\CapCalibrator\cache\synth_data
Renderer log file: C:\Users\14993\Documents\STORM-Net-master\CapCalibrator\cache\render_log.txt

Thanks for helping!

**Comment by yoterel** [comment]
Hi, To be honest everything  in terms of environment looks good to me, and googling this issue seems to hint that this problem is with unicode letters in the path. By any chance do you have non-english characters in any of the paths? could you try to change the line:
File "C:\Users\14993\Documents\STORM-Net-master\CapCalibrator\file_io.py", line 176, in is_process_active
`output = subprocess.check_output(call).decode()`

and instead try:
`output = subprocess.check_output(call).decode("utf-8")`
or perhaps
`output = subprocess.check_output(call).decode("cp437")`

and tell me if it worked?

**Comment by jyzhuu** [comment]
Hi there, thank you for the suggestion. I actually have googled this issue and tried many of these solutions, but none of them worked. However, the great news is that I tried another pc to run this today and it worked! So I think we might just leave this issue as a mystery.

**Comment by yoterel** [comment]
Thanks for the input, I will close the issue for now (feel free to reopen).
