### ISSUE TITLE
How can I make my own template for the offline step?

### ISSUE THREAD

**Issue by qguo7749** [yoterel/STORM-Net#12]
Hi,

I saw that there were example templates for adults and kids in the repo. Based on my understanding, it is better to have a template for each new cap in the offline step. How can I make a template? I could not find information on this topic from your papers. Looking forward to your reply.
Thank you!

**Comment by yoterel** [comment]
Hi,
There are a couple of ways we tried previously: you can purchase or 3D print an anatomically correct head (for example using an MRI scan, or some publicly available model) that the cap should fit on, and measure directly using either a Polhemus (magnetic measurement) device, or taking a video of the head and cap and reconstruct it using some photogrammetry method (such as colmap, Metashape, opensfm, etc.).

Another way is if you have the cap manufacturer provide you with the locations of the sensors using their software, and sometimes even jointly with anatomical positions (for example Artinis have exactly such software).

Feel free to ask more questions if needed.
