### ISSUE TITLE
Long load time for json synth data

### ISSUE THREAD

**Issue by Uz-Hakim** [yoterel/STORM-Net#4]
Approx 20s per json, with 100,000 iterations = 20 days to load.  

Python version 3.7.16
Windows 10

**Comment by Uz-Hakim** [comment]
Trying to load the first 10 json files of my synth data returns an error:  

```
File "load_ten_json_test.py", line 84, in <module>
    X, Y = file_io.load_raw_json_db(datadir)
  File "C:\Users\uzair\Desktop\stormnet_test\STORM-Net-master\CapCalibrator\file_io.py", line 273, in load_raw_json_db
    timesteps_per_sample = X[0].shape[0]
IndexError: list index out of range
```
Investigating further shows the valid stickers in each file: 

```
[False, False, False, False, False, False, False]
[False, False, False, False, False, False, False]
[False, False, False, False, False, False, False]
[False, False, False, False, False, False, False]
[False, False, False, False, False, False, False]
[False, False, False, False, False, False, True]
[False, False, False, False, False, False, True]
[False, False, False, False, False, False, True]
[False, False, False, False, False, False, True]
[False, False, False, False, False, False, True]
```

In comparison synthetic data generated from the provided template file gives all true for valid_stickers and the json files load fine.

**Comment by Uz-Hakim** [comment]
This seems to occur only when using the command line to run the training via train.py script. Using the gui interface which seems to call torch_train.py (rather than train.py) seems to load data fine

**Comment by yoterel** [comment]
Hi there, torch_train.py is indeed the correct training script, the train.py script is deprecated.
I will move it into a legacy folder to avoid this problem in the future, sorry for the misunderstanding.

also updated README to reflect this.
