### ISSUE TITLE
Training model with gpu, incorrect batching? 

### ISSUE THREAD

**Issue by Uz-Hakim** [yoterel/STORM-Net#5]
Running the training through the gui with gpu_id = 0 (only 1 cuda enabled gpu) provides the output in terminal: 

![image](https://user-images.githubusercontent.com/56116794/229567496-228ecb5b-9e89-4fc4-ba5f-aa7d53f9beea.png)

Running the same training through the command-line provides the following output in terminal: 

![image](https://user-images.githubusercontent.com/56116794/229567664-ed8ff922-260d-4b84-a082-12cc50ea7f83.png)

Both are snippets of the fulloutput. 

The second finishes the training with nowhere near the required val loss, whilst the first hangs at epoch 49 and progresses no further.

**Comment by Uz-Hakim** [comment]
Function `utils.split_data` splits the data into 6 for the training and 2 for validating. 
Using authors provided data splits the data into 80,000 for training and 20,000 for validating. 

Only 8 values are defined as not None in the` file_io.load_raw_json_db` function. Seems to be not enough 'valid_stickers'

Issue with how the synthetic data is generated? The model coordinates are in the correct format.

**Comment by Uz-Hakim** [comment]
Recreating synthetic data with the same template file changed the split to 8 training and 3 validating.

**Comment by Uz-Hakim** [comment]
Redoing the template file in the exact same way seems to have fixed the issue. I've attached both files here incase anyone wants to investigate further.

[works.txt](https://github.com/yoterel/STORM-Net/files/11147403/works.txt)
[doesnt_work.txt](https://github.com/yoterel/STORM-Net/files/11147406/doesnt_work.txt)

**Comment by yoterel** [comment]
Might be the file line ending. but as you managed to solve this by replicating the format form the example models issue is closed. Thank you for the update !

P.S. you can name the other sensors in any way you like, for example S1, D1, S2, D2, etc. (doesn't have to be 0, 1, 2, 3, ...)
