### ISSUE TITLE
Can't activate STORM  - problem with torch

### ISSUE THREAD

**Issue by ninabesserilan** [yoterel/STORM-Net#8]
OSError: [WinError 126] The specified module could not be found. Error loading "C:\Users\User\miniconda3\envs\env\lib\site-packages\torch\lib\shm.dll" or one of its dependencies.

**Comment by yoterel** [comment]
This problem can be solved by doing 
`conda install cudatoolkit`
(after installation, when the environment is activated)

see [here](https://stackoverflow.com/questions/74594256/pytorch-error-loading-lib-site-packages-torch-lib-shm-dll-or-one-of-its-depen) for further detail
