### ISSUE TITLE
Problem with json files created in the rendering of synthetic data/ Offline Step 

### ISSUE THREAD

**Issue by kaotten** [yoterel/STORM-Net#9]
Hi, 

we managed to install Stormnet, however, we run into the following problem: for the Offline Step, rendering the synthetic data (with all default settings) runs and creates a cache/synth_data folder full with json files. However, these files do not seem to be correct. Under "valid stickers" they are always filled with "false". The training process also does not work with these data. 

For reference I attached one of the json files. We don´t know what causes the problem and we are happy for any help!

[image_000005.json](https://github.com/yoterel/STORM-Net/files/14311733/image_000005.json)

**Comment by yoterel** [comment]
Hi, can you upload/share the template model file you used to generate the synthetic data ?

**Comment by kaotten** [comment]
Yes, I used the one you provided as model on your github. It´s the adultTemplate.txt, however, the same problem seemed to occur for other templates. 
[adultTemplate.txt](https://github.com/yoterel/STORM-Net/files/14315063/adultTemplate.txt)

**Comment by yoterel** [comment]
Sorry for the late response. I will attempt to reproduce this. Can you let me know what are the values you use for creating the render files ?

**Comment by kaotten** [comment]
I used all the default values, so I really did not change anything there. 

However, it may be important to mention that a colleague from another working group did not have the same problem even though he used the same scripts and templates. We tried to figure out what made the difference and found that he did not install the environment based on your environment.yml file, but instead already had all the packages on his computer. Therefore, we suspected that the problem might be caused by the difference in environments. 

We were wondering if we could get the specific version numbers of all the packages that you are using so we can check them?

And another question about the contents of the wrong json files. Is that the initial format? Because when we were running the rendering via the command line, it seemed like not really running, but still with no errors.

**Comment by yoterel** [comment]
Hi, sorry for the late reply.

I have installed STORM-Net on a a clean setup (windows10, python 3.8,  following the README instructions), but I have not been able to reproduce this problem (my generated json files include true values).
Can you please post your python version, operating system version, and the output from "conda list" ? then I could perhaps reproduce your problem and solve it.

In any case, perhaps you can try by manually setting up a new environment with conda:

`conda create --name storm python=3.8`
then activate it:
`conda activate storm`

Then run the following commands one by one (accept the question by pressing Y everytime if asked):
`conda install pytorch torchvision torchaudio pytorch-cuda=11.8 -c pytorch -c nvidia`
`conda install anaconda::scikit-learn`
`conda install conda-forge::imageio`
`conda install conda-forge::matplotlib`
`python -m pip install polyscope`
`pip install tensorflow `
`pip install opencv-python==4.5.3.56`
`pip install gsoup`

This will mostly just install latest versions of all of these libraries, which should work fine (except opencv-python, please use the version written above).

> And another question about the contents of the wrong json files. Is that the initial format? 

Sorry I don't think I understand the question here. These jsons are the result of a synthetic scene being rendered and then the location of the virtual landmarks recorded to the file. The data is written in a json just for simplicity.
Can you perhaps rephrase or explain better what you want to know ?

**Comment by yoterel** [comment]
Has this been resolved?
